name: Lotto purchase (cron)
on:
  schedule:
    # 매 주 수요일 오후 12시, Github Actions 에서는 UTC 기준으로 실행됨
    # https://elmah.io/tools/cron-parser/
    - cron: '0 3 * * 3'

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rich-automation/lotto-actions@0.0.4
        with:
          id: ${{ secrets.ID }}
          pwd: ${{ secrets.PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
